### ISSUE TITLE
About “warm-up” and how does TSSL-BP encourage spike generation?

### ISSUE THREAD

**Issue by pkuxmq** [stonezwr/TSSL-BP#2]
Hi, thanks for your work and sharing. I have several questions about the paper and the code.

1. The paper claims that a warm-up mechanism with surrogate function is used before applying TSSL-BP. But in the code, it seems that this is used throughout the training once the activation is lower than the threshold. Is it inconsistent?

2. I wonder how could TSSL-BP encourage spike generation. For example, if the first spike time for a neuron at last layer during forward pass is t1, then for the target spikes whose time should be less than t1, its supervision information cannot be back-propagated because there is no spike before t1 and thus TSSL-BP will not back-propagate. Also, at the timestep when there should be a target spike but the model does not generate one currently, the supervision is not back-propagated at this time as well. So how could TSSL-BP encourage spike generation? Previous works regarding time-based learning only consider the time for one spike, e.g. the first spike, but in this work it seems spike generation is necessary in order to fit the target sequence.

3. I tried your code on cifar10 both directly and after commenting out the TSSL-BP (i.e. only use your “warm-up” with surrogate function for BP). Surprisingly, I found that they have very similar training procedures and performances. I wonder if you have done ablation study on this “warm-up”? Is it possible that actually it is still this surrogate function that back-propagate most information (e.g. spike generation)?

Hope for your reply and thank you very much in advance.

**Comment by stonezwr** [comment]
Hello, 

Thanks for your interest in our work. 

In some sense, you are right. Our proposed method cannot handle the spike generation very well. In our derivation, the gradient is calculated based on the spike time with the assumption that the spike exists. Therefore, the warmup is necessary to handle the spike generation when no spike fires.

The code shared here has been updated several times and is still in progress. We hope to find a better way to apply the warm-up. One thought is that we can hybrid the TSSL-BP with a rate-based BP rule (e.g. surrogate gradient) so that the former one can handle firing time and the latter one handles the firing count.

Thanks.

**Comment by pkuxmq** [comment]
Thanks for your reply. And I have another question that if the objective is to construct a low time step snn, then is it necessary to consider the firing time much? Because low time step means large discretization error on time, and maybe only 5 time step cannot distinguish the update over time at all. Does TSSL-BP work better for long time step?

Thanks.

**Comment by stonezwr** [comment]
To my understanding, datasets with more time steps (like neuromorphic datasets, audio datasets) are more suitable for SNNs. We conducted experiments on these kinds of datasets and obtained good performance. We'll share our results in the future work. Current, one potential problem is that more time steps lead to extremely large time and memory cost due to the nature of BPTT. Therefore, we're working the code to reduce the cost. 

Thanks.

**Comment by pkuxmq** [comment]
Thank you very much.

**Comment by GitHubmalajava** [comment]
> Hi, thanks for your work and sharing. I have several questions about the paper and the code.
> 
> 1. The paper claims that a warm-up mechanism with surrogate function is used before applying TSSL-BP. But in the code, it seems that this is used throughout the training once the activation is lower than the threshold. Is it inconsistent?
> 2. I wonder how could TSSL-BP encourage spike generation. For example, if the first spike time for a neuron at last layer during forward pass is t1, then for the target spikes whose time should be less than t1, its supervision information cannot be back-propagated because there is no spike before t1 and thus TSSL-BP will not back-propagate. Also, at the timestep when there should be a target spike but the model does not generate one currently, the supervision is not back-propagated at this time as well. So how could TSSL-BP encourage spike generation? Previous works regarding time-based learning only consider the time for one spike, e.g. the first spike, but in this work it seems spike generation is necessary in order to fit the target sequence.
> 3. I tried your code on cifar10 both directly and after commenting out the TSSL-BP (i.e. only use your “warm-up” with surrogate function for BP). Surprisingly, I found that they have very similar training procedures and performances. I wonder if you have done ablation study on this “warm-up”? Is it possible that actually it is still this surrogate function that back-propagate most information (e.g. spike generation)?
> 
> Hope for your reply and thank you very much in advance.

Hi，You said you copied their code, I have a problem, I want to know how to modify the default configuration of the YAML file of this code force, I changed the file path, but the because ‘data_path’ ，this program still cannot run, can you give me some solutions。
Thank you ,Looking forward to your reply
