### ISSUE TITLE
about the psp computing and the desired inputs

### ISSUE THREAD

**Issue by XDUSPONGE** [stonezwr/TSSL-BP#4]
Thanks for sharing your job. And I have two questions?
1、The psp computing, In my opinion, dv/dt = -v + RI, and  syn = syn - syn / tau_s + inputs[..., t], so why should syns[...,t] = syn/ tau_s
2. Why did you define the desired output when n_steps >=10 like [0 1 0 1 0 1 0 1 0 1]
    In the 5 steps, I can understand may be the first time step, it can not spike, so it is [0 1 1 1 1]
Thanks very much

**Comment by stonezwr** [comment]
Thanks for your interest in our work.

1.For the synaptic kernel, usually, the inputs in "syn = syn - syn / tau_s + inputs[..., t]" should be divided by tau_s so that its integration through all the time equals 1.
2. The desired output is manually defined. We didn't explore what kind of output is better for training in this work. You can set it to any other spike trains you want.

**Comment by XDUSPONGE** [comment]
Ok, thanks for your reply
